services:
  - type: web
    name: blivhort-ai
    env: node
    rootDir: .
    buildCommand: |
      set -e
      export PYTHONPATH="$PWD/python_packages"
      mkdir -p python_packages
      python3 -m pip install --no-cache-dir --no-warn-script-location --target python_packages setuptools==70.0.0 packaging wheel || true
      PUPPETEER_SKIP_DOWNLOAD=true npm install --no-audit --no-fund
      npm rebuild better-sqlite3 --update-binary || true
      # Disable source builds on Render since distutils may be missing; prefer prebuilt
      :
      if [ -f requirements.txt ]; then \
        python3 -m pip install --no-cache-dir --no-warn-script-location --target python_packages -r requirements.txt; \
      else \
        echo 'No Python requirements.txt found, skipping'; \
      fi
    startCommand: >
      bash -lc "mkdir -p data/uploads tmp &&
      rm -rf uploads &&
      ln -s data/uploads uploads &&
      npm rebuild better-sqlite3 --build-from-source || true &&
      node server.js"
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.11.0
      - key: PIP_USER
        value: "0"
      - key: PYTHONPATH
        value: "/opt/render/project/src/python_packages"
      - key: SETUPTOOLS_USE_DISTUTILS
        value: "local"
      - key: ALLOW_RUNTIME_SQLITE_REBUILD
        value: "0"
      - key: YARN_ENABLE_IMMUTABLE_INSTALLS
        value: "false"
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_ID
        value: gpt-5
      - key: PYTHON_BIN
        value: python3
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: NODE_OPTIONS
        value: "--enable-source-maps --max-old-space-size=768"
      - key: NEXT_DATA_MAX_BYTES
        value: "2500000"
      - key: WARM_CONCURRENCY
        value: "1"
      - key: PUBLIC_URL
        value: "https://blivhort-ai.onrender.com"
      - key: PERSIST_PREFER
        value: "true"
      - key: PERSIST_ALWAYS_WRITE
        value: "true"
      - key: WARM_ALL_ON_START
        value: "true"
      - key: WARM_MAX_HEARINGS
        value: "0"
      - key: WARM_RETRY_ATTEMPTS
        value: "2"
      - key: INTERNAL_API_TIMEOUT_MS
        value: "1500000"
      - key: DISABLE_SEARCH_REMOTE_BACKFILL
        value: "true"
      - key: INDEX_REFRESH_MS
        value: "21600000"
      - key: CRON_ENABLED
        value: "1"
      - key: CRON_INDEX_SCHEDULE
        value: "0 */6 * * *"
      - key: CRON_HEARING_REFRESH
        value: "*/30 * * * *"
      - key: SESSION_SECRET
        generateValue: true
    disks:
      - name: app-data
        mountPath: /opt/render/project/src/data
        sizeGB: 1