services:
  - type: web
    name: blivhort-ai
    env: node
    rootDir: .
    buildCommand: |
      PUPPETEER_SKIP_DOWNLOAD=true npm install --no-audit --no-fund
      mkdir -p python_packages
      python3 -m pip install --no-cache-dir --no-warn-script-location --target python_packages -r requirements.txt
    startCommand: >
      bash -lc "mkdir -p data/uploads tmp &&
      rm -rf uploads &&
      ln -s data/uploads uploads &&
      node server.js"
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.12.2
      - key: PIP_USER
        value: "0"
      - key: PYTHONPATH
        value: "/opt/render/project/src/python_packages"
      - key: YARN_ENABLE_IMMUTABLE_INSTALLS
        value: "false"
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_ID
        value: gpt-5
      - key: PYTHON_BIN
        value: python3
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: NODE_OPTIONS
        value: "--enable-source-maps --max-old-space-size=512"
      - key: SESSION_SECRET
        generateValue: true
    disks:
      - name: app-data
        mountPath: /opt/render/project/src/data
        sizeGB: 1